<?php

namespace Nekudo\Angela\Broker;

class Message
{
    /**
     * @var string $messageId Unique message id generated by broker.
     */
    protected $messageId = '';

    /**
     * @var string $callbackId Id used to identify responses to a message.
     */
    protected $callbackId = '';

    /**
     * @var string $type Job type. Can be "normal" or "background".
     */
    protected $type = 'normal';

    /**
     * @var string $body Actual message content.
     */
    protected $body = '';

    /**
     * @param string $messageId
     */
    public function setMessageId(string $messageId)
    {
        $this->messageId = $messageId;
    }

    /**
     * @return string
     */
    public function getMessageId() : string
    {
        return $this->messageId;
    }

    /**
     * @param string $callbackId
     */
    public function setCallbackId(string $callbackId)
    {
        $this->callbackId = $callbackId;
    }

    /**
     * @return string
     */
    public function getCallbackId() : string
    {
        return $this->callbackId;
    }

    /**
     * @param string $type
     */
    public function setType(string $type)
    {
        if ($type !== 'normal' && $type !== 'background') {
            throw new \InvalidArgumentException('Message type has to be normal or background.');
        }
        $this->type = $type;
    }

    /**
     * @return string
     */
    public function getType() : string
    {
        return $this->type;
    }

    /**
     * @param string $body
     */
    public function setBody(string $body)
    {
        $this->body = $body;
    }

    /**
     * @return string
     */
    public function getBody() : string
    {
        return $this->type;
    }
}
